name: generate-all-job
on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            markdown
            bleach
      - name: generate all
        run: bash ./bin/main.sh
